function [ ] = buildStimParamFileIssaDicarlo()
% BuildStimParamFileSocialInt
%Creates a .m file containing cell arrays detailing the parameters of a
%particular stimulus set. Julia produced 4 orders of the videos detailed
%below.

%File produced 2 Cell Arrays. The first is a ParamArray, with the name of
%the video. {{VideoID1; {label1}; {label2}...}{VideoID2; {label1};
%{label2}...}. The second is a TriggerLabels, containing all possible labels. 

categoryLabels = {'typical','atypical' };

paramArray = {...
{'im046.bmp'; 'atypical'};...
{'im054.bmp'; 'atypical'};...
{'im058.bmp'; 'atypical'};...
{'im063.bmp'; 'atypical'};...
{'im071.bmp'; 'atypical'};...
{'im078.bmp'; 'atypical'};...
{'im095.bmp'; 'atypical'};...
{'im097.bmp'; 'atypical'};...
{'im098.bmp'; 'atypical'};...
{'im108.bmp'; 'atypical'};...
{'im111.bmp'; 'atypical'};...
{'im112.bmp'; 'atypical'};...
{'im114.bmp'; 'atypical'};...
{'im041.bmp'; 'typical'};...
{'im057.bmp'; 'typical'};...
{'im065.bmp'; 'typical'};...
{'im073.bmp'; 'typical'};...
{'im118.bmp'; 'typical'};...
{'im119.bmp'; 'typical'};...
{'im121.bmp'; 'typical'};...
{'im122.bmp'; 'typical'}};

pictureLabels = {...
    'im046';...
    'im054';...
    'im058';...
    'im063';...
    'im071';...
    'im078';...
    'im095';...
    'im097';...
    'im098';...
    'im108';...
    'im111';...
    'im112';...
    'im114';...
    'im041';...
    'im057';...
    'im065';...
    'im073';...
    'im118';...
    'im119';...
    'im121';...
    'im122'};

save('StimParamsIssaDicarlo.mat','paramArray','categoryLabels','pictureLabels')


