function [ ] = buildStimParamFileSocialStills()


categoryLabels = {'all','oneFace','twoFace','oneNHP','twoNHP','obsFace'};

paramArray = {...
{'chase9.bmp', 'all','twoNHP','twoFace'};...
{'chase12.bmp', 'all','twoNHP','twoFace'};...  
{'chase16.bmp', 'all','twoNHP','oneFace','obsFace'};...
{'chase19.bmp', 'all','twoNHP','twoFace'};...
{'control7.bmp', 'all','twoNHP','oneFace','obsFace'};... 
{'control8.bmp', 'all','twoNHP','twoFace'};...     
{'control30.bmp', 'all','twoNHP','twoFace'};... 
{'control67.bmp', 'all','twoNHP','twoFace'};... 
{'fight8.bmp', 'all','twoNHP','oneFace','obsFace'};...  
{'fight13.bmp', 'all','twoNHP','oneFace','obsFace'};...  
{'fight29.bmp', 'all','twoNHP','twoFace'};...
{'fight33.bmp', 'all','twoNHP','twoFace'};... 
{'foragekin1.bmp', 'all','twoNHP','oneFace','obsFace'};...
{'foragekin18.bmp', 'all','twoNHP','twoFace'};...
{'foragekin22.bmp', 'all','twoNHP','twoFace'};...
{'foragekin28.bmp', 'all','twoNHP','twoFace'};...
{'friendsclose4.bmp', 'all','twoNHP','twoFace'};...  
{'friendsclose7.bmp', 'all','twoNHP','twoFace'};...
{'friendsclose8.bmp', 'all','twoNHP','twoFace'};... 
{'friendsclose11.bmp', 'all','twoNHP','twoFace'};...
{'friendsforaging1.bmp', 'all','twoNHP','twoFace'};...
{'friendsforaging9.bmp', 'all','twoNHP','twoFace'};... 
{'friendsforaging11.bmp', 'all','twoNHP','twoFace'};... 
{'friendsforaging14.bmp', 'all','twoNHP','twoFace'};...
{'friendsgroom33.bmp', 'all','twoNHP','twoFace'};...
{'friendsgroom36.bmp', 'all','twoNHP','twoFace'};...
{'friendsgroom41.bmp', 'all','twoNHP','twoFace'};...
{'friendsgroom53.bmp', 'all','twoNHP','twoFace'};... 
{'groomkin1.bmp', 'all','twoNHP','oneFace','obsFace'};...
{'groomkin3.bmp', 'all','twoNHP','twoFace'};...
{'groomkin13.bmp', 'all','twoNHP','twoFace'};...     
{'groomkin16.bmp', 'all','twoNHP','twoFace'};...      
{'hold5.bmp', 'all','twoNHP','twoFace'};...     
{'hold6.bmp', 'all','twoNHP','twoFace'};... 
{'hold15.bmp', 'all','twoNHP','oneFace','obsFace'};...               
{'hold17.bmp', 'all','twoNHP','twoFace'};...           
{'mount3.bmp', 'all','twoNHP','twoFace'};...  
{'mount10.bmp', 'all','twoNHP','twoFace'};...         
{'mount19.bmp', 'all','twoNHP','twoFace'};...          
{'mount28.bmp', 'all','twoNHP','twoFace'};...     
{'controlonemonkey14.bmp', 'all', 'oneNHP','oneFace'};...
{'controlonemonkey2.bmp', 'all','oneNHP','oneFace'};...  
{'controlonemonkey12.bmp', 'all','oneNHP','oneFace'};...  
{'controlonemonkey18.bmp', 'all','oneNHP','oneFace'};... 
};

pictureLabels = {...
'chase9';...
'chase12';...  
'chase16';...
'chase19';...
'control7';... 
'control8';...     
'control30';... 
'control67';... 
'fight8';...  
'fight13';...  
'fight29';...
'fight33';... 
'foragekin1';...
'foragekin18';...
'foragekin22';...
'foragekin28';...
'friendsclose4';...  
'friendsclose7';...
'friendsclose8';... 
'friendsclose11';...
'friendsforaging1';...
'friendsforaging9';... 
'friendsforaging11';... 
'friendsforaging14';...
'friendsgroom33';...
'friendsgroom36';...
'friendsgroom41';...
'friendsgroom53';... 
'groomkin1';...
'groomkin3';...
'groomkin13';...     
'groomkin16';...      
'hold5';...     
'hold6';... 
'hold15';...               
'hold17';...           
'mount3';...  
'mount10';...         
'mount19';...          
'mount28';...     
'controlonemonkey14';...
'controlonemonkey2';...  
'controlonemonkey12';...  
'controlonemonkey18';... 
};
save('StimParamsSocialStills.mat','paramArray','categoryLabels','pictureLabels')


