function [ ] = buildVideotoClipMapFile()
% buildVideotoClipMapFile
%Creates a .mat file containing cell arrays detailing the timing of clips within 
%a particular stimulus set. Julia produced 4 orders of the videos detailed
%below.

T_start = 0; T_end = 1;

A = {...
    'ConcatenatedSocial_order1.avi';
    {'Order1Interaction_fighting.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_chasing.avi'; T_start; T_end}; ...
    {'Order1Interaction_mounting.avi'; T_start; T_end}; ...
    {'Order1Interaction_grooming2.avi'; T_start; T_end}; ...
    {'Order1MonkLeft_Order1MonkRight_5.avi'; T_start; T_end}; ...
    {'Order1GoalLeft_Order1GoalRight_2.avi'; T_start; T_end}; ...
    {'Order2LandscapesFull_3.avi'; T_start; T_end}; ...
    {'Order1MonkLeft_Order1MonkRight_1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_fighting.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_grooming2.avi'; T_start; T_end}; ...
    {'Order1Interaction_chasing.avi'; T_start; T_end}; ...
    {'Order2LandscapesFull_1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_grooming1.avi'; T_start; T_end}; ...
    {'Order1GoalLeft_Order1GoalRight_1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_mounting.avi'; T_start; T_end}; ...
    {'obj_interact1_2.avi'; T_start; T_end}; ...
    {'obj_interact1_1.avi'; T_start; T_end}; ...
    {'Order1Interaction_grooming1.avi'; T_start; T_end}; ...
    };

B = {...
    'ConcatenatedSocial_order2.avi';
    {'Dephased_Order1Interaction_chasing.avi'; T_start; T_end}; ...
    {'Order2LandscapesFull_3.avi'; T_start; T_end}; ...
    {'obj_interact1_2.avi'; T_start; T_end}; ...
    {'Order2LandscapesFull_1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_grooming1.avi'; T_start; T_end}; ...
    {'Order1Interaction_fighting.avi'; T_start; T_end}; ...
    {'Order1GoalLeft_Order1GoalRight_2.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_grooming2.avi'; T_start; T_end}; ...
    {'Order1Interaction_mounting.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_mounting.avi'; T_start; T_end}; ...
    {'Order1Interaction_grooming2.avi'; T_start; T_end}; ...
    {'Order1MonkLeft_Order1MonkRight_5.avi'; T_start; T_end}; ...
    {'Order1MonkLeft_Order1MonkRight_1.avi'; T_start; T_end}; ...
    {'Order1Interaction_grooming1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_fighting.avi'; T_start; T_end}; ...
    {'Order1GoalLeft_Order1GoalRight_1.avi'; T_start; T_end}; ...
    {'Order1Interaction_chasing.avi'; T_start; T_end}; ...
    {'obj_interact1_1.avi'; T_start; T_end}; ...
    };

C = {...
    'ConcatenatedSocial_order3.avi';
    {'obj_interact1_2.avi'; T_start; T_end}; ...
    {'Order1Interaction_mounting.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_grooming1.avi'; T_start; T_end}; ...
    {'Order2LandscapesFull_3.avi'; T_start; T_end}; ...
    {'Order1GoalLeft_Order1GoalRight_1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_grooming2.avi'; T_start; T_end}; ...
    {'Order1Interaction_grooming1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_chasing.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_fighting.avi'; T_start; T_end}; ...
    {'Order1Interaction_grooming2.avi'; T_start; T_end}; ...
    {'obj_interact1_1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_mounting.avi'; T_start; T_end}; ...
    {'Order1Interaction_fighting.avi'; T_start; T_end}; ...
    {'Order2LandscapesFull_1.avi'; T_start; T_end}; ...
    {'Order1GoalLeft_Order1GoalRight_2.avi'; T_start; T_end}; ...
    {'Order1MonkLeft_Order1MonkRight_5.avi'; T_start; T_end}; ...
    {'Order1MonkLeft_Order1MonkRight_1.avi'; T_start; T_end}; ...
    {'Order1Interaction_chasing.avi'; T_start; T_end}; ...
    };

D = {...
    'ConcatenatedSocial_order4.avi';
    {'Order1Interaction_mounting.avi'; T_start; T_end}; ...
    {'Order1MonkLeft_Order1MonkRight_1.avi'; T_start; T_end}; ...
    {'Order1GoalLeft_Order1GoalRight_1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_grooming1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_grooming2.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_fighting.avi'; T_start; T_end}; ...
    {'Order1MonkLeft_Order1MonkRight_5.avi'; T_start; T_end}; ...
    {'obj_interact1_1.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_mounting.avi'; T_start; T_end}; ...
    {'Dephased_Order1Interaction_chasing.avi'; T_start; T_end}; ...
    {'Order1Interaction_chasing.avi'; T_start; T_end}; ...
    {'Order2LandscapesFull_1.avi'; T_start; T_end}; ...
    {'Order1GoalLeft_Order1GoalRight_2.avi'; T_start; T_end}; ...
    {'Order1Interaction_grooming2.avi'; T_start; T_end}; ...
    {'Order2LandscapesFull_3.avi'; T_start; T_end}; ...
    {'Order1Interaction_fighting.avi'; T_start; T_end}; ...
    {'Order1Interaction_grooming1.avi'; T_start; T_end}; ...
    {'obj_interact1_2.avi'; T_start; T_end}; ...
    };

VideoToClipMap = {A, B, C, D};

%Timing - According to Julia, 15 frames of gray, 83 frames of video, 15
%frames of gray, at a rate of 29.97 frames/sec
grayframecount = 15;
clipframecount = 83;
frame_rate = 29.97;
frame_duration = (1/frame_rate)*1e3; %frame duration in ms.
time = 0; %Keeping count of time
Time_array = zeros(length(A),1);
%Each Block is 15 Frames of gray, 83 frames of video, 
%with a final gray block @ the end.
ii = 1;
loop = length(Time_array)*2; %some odd thing with the array extending
while ii < loop
  %time in for grays + time to end = start
  time = time + frame_duration*(grayframecount);
  Time_array(ii) = floor(time);
  %Time after the 83 frames of clip = end
  time = time + frame_duration*(clipframecount);
  Time_array(ii+1) = floor(time);
  ii = ii + 2;
end
%The Last value isn't used.

% Adding Timing
for ii = 1:4
  hh = 0;
  for jj = 2:19
      hh = hh + 1;
      VideoToClipMap{ii}{jj}{2} = Time_array(hh);
      hh = hh + 1;
      VideoToClipMap{ii}{jj}{3} = Time_array(hh);
  end
end
subTriggerArray = VideoToClipMap;
save('socialSceneConcatSubTriggers.mat','subTriggerArray');
end

