function [ ] = buildStimParamFileSocialVids_V2()
% BuildStimParamFileSocialInt
%Creates a .m file containing cell arrays detailing the parameters of a
%particular stimulus set.

%File produced 2 Cell Arrays. The first is a ParamArray, with the name of
%the video. {{VideoID1; {label1}; {label2}...}{VideoID2; {label1};
%{label2}...}. The second is a TriggerLabels, containing all possible labels. 

% For experiment run 2018.10.10

categoryLabels = {'objects', 'twoMonkeys', 'twoHumans', 'interaction', 'socialInteraction', 'nonInteraction', ...
    'chasing', 'fighting', 'foraging', 'foraging', 'grooming','holding','landscape','goalDir',...
    'idle','mounting','observing','scramble','sitting'};

paramArray = {...
{'scramble_3001.avi'; 'scramble'}; ...
{'scramble_3002.avi'; 'scramble'}; ...
{'scramble_3003.avi'; 'scramble'}; ...
{'scramble_3004.avi'; 'scramble'}; ...
{'scramble_3005.avi'; 'scramble'}; ...

{'landscape_4001.avi'; 'landscape'}; ...
{'landscape_4002.avi'; 'landscape'}; ...
{'landscape_4003.avi'; 'landscape'}; ...
{'landscape_4004.avi'; 'landscape'}; ...
{'landscape_4005.avi'; 'landscape'}; ...

{'objects_2101.avi'; 'objects'; 'interaction'}; ...
{'objects_2102.avi'; 'objects'; 'interaction'}; ...
{'objects_2103.avi'; 'objects'; 'interaction'}; ...
{'objects_2104.avi'; 'objects'; 'interaction'}; ...
{'objects_2105.avi'; 'objects'; 'interaction'}; ...

{'humanChasing_1111.avi'; 'twoHumans'; 'socialInteraction'; 'chasing';'highMotion'}; ...
{'monkeyChasing_1111.avi'; 'twoMonkeys'; 'socialInteraction'; 'chasing';'highMotion'}; ...
{'monkeyChasing_1112.avi'; 'twoMonkeys'; 'socialInteraction'; 'chasing';'highMotion'}; ...
{'monkeyChasing_1113.avi'; 'twoMonkeys'; 'socialInteraction'; 'chasing';'highMotion'}; ...
{'monkeyChasing_1114.avi'; 'twoMonkeys'; 'socialInteraction'; 'chasing';'highMotion'}; ...
{'monkeyChasing_1115.avi'; 'twoMonkeys'; 'socialInteraction'; 'chasing';'highMotion'}; ...

{'humanFighting_1121.avi'; 'twoHumans'; 'socialInteraction'; 'fighting'}; ...
{'monkeyFighting_1121.avi'; 'twoMonkeys'; 'socialInteraction'; 'fighting'}; ...
{'monkeyFighting_1122.avi'; 'twoMonkeys'; 'socialInteraction'; 'fighting'}; ...
{'monkeyFighting_1123.avi'; 'twoMonkeys'; 'socialInteraction'; 'fighting'}; ...
{'monkeyFighting_1124.avi'; 'twoMonkeys'; 'socialInteraction'; 'fighting'}; ...
{'monkeyFighting_1135.avi'; 'twoMonkeys'; 'socialInteraction'; 'fighting'}; ...

{'humanMounting_1131.avi'; 'twoHumans'; 'socialInteraction'; 'mounting'}; ...
{'monkeyMounting_1131.avi'; 'twoMonkeys'; 'socialInteraction'; 'mounting'}; ...
{'monkeyMounting_1132.avi'; 'twoMonkeys'; 'socialInteraction'; 'mounting'}; ...
{'monkeyMounting_1133.avi'; 'twoMonkeys'; 'socialInteraction'; 'mounting'}; ...
{'monkeyMounting_1134.avi'; 'twoMonkeys'; 'socialInteraction'; 'mounting'}; ...
{'monkeyMounting_1135.avi'; 'twoMonkeys'; 'socialInteraction'; 'mounting'}; ...

{'humanGrooming_1141.avi'; 'twoHumans'; 'socialInteraction'; 'grooming'}; ...
{'monkeyGrooming_1141.avi'; 'twoMonkeys'; 'socialInteraction'; 'grooming'}; ...
{'monkeyGrooming_1142.avi'; 'twoMonkeys'; 'socialInteraction'; 'grooming'}; ...
{'monkeyGrooming_1143.avi'; 'twoMonkeys'; 'socialInteraction'; 'grooming'}; ...
{'monkeyGrooming_1144.avi'; 'twoMonkeys'; 'socialInteraction'; 'grooming'}; ...
{'monkeyGrooming_1145.avi'; 'twoMonkeys'; 'socialInteraction'; 'grooming'}; ...

{'humanHolding_1151.avi'; 'twoHumans'; 'socialInteraction'; 'holding'}; ...
{'monkeyHolding_1151.avi'; 'twoMonkeys'; 'socialInteraction'; 'holding'}; ...
{'monkeyHolding_1152.avi'; 'twoMonkeys'; 'socialInteraction'; 'holding'}; ...
{'monkeyHolding_1153.avi'; 'twoMonkeys'; 'socialInteraction'; 'holding'}; ...
{'monkeyHolding_1154.avi'; 'twoMonkeys'; 'socialInteraction'; 'holding'}; ...
{'monkeyHolding_1155.avi'; 'twoMonkeys'; 'socialInteraction'; 'holding'}; ...

{'humanFollowing_1161.avi'; 'twoHumans'; 'socialInteraction'; 'following'}; ...
{'monkeyFollowing_1161.avi'; 'twoMonkeys'; 'socialInteraction'; 'following'}; ...
{'monkeyFollowing_1162.avi'; 'twoMonkeys'; 'socialInteraction'; 'following'}; ...
{'monkeyFollowing_1163.avi'; 'twoMonkeys'; 'socialInteraction'; 'following'}; ...
{'monkeyFollowing_1164.avi'; 'twoMonkeys'; 'socialInteraction'; 'following'}; ...
{'monkeyFollowing_1165.avi'; 'twoMonkeys'; 'socialInteraction'; 'following'}; ...

{'humanObserving_1171.avi'; 'twoHumans'; 'socialInteraction'; 'observing'}; ...
{'monkeyObserving_1171.avi'; 'twoMonkeys'; 'socialInteraction'; 'observing'}; ...
{'monkeyObserving_1172.avi'; 'twoMonkeys'; 'socialInteraction'; 'observing'}; ...
{'monkeyObserving_1173.avi'; 'twoMonkeys'; 'socialInteraction'; 'observing'}; ...
{'monkeyObserving_1174.avi'; 'twoMonkeys'; 'socialInteraction'; 'observing'}; ...
{'monkeyObserving_1175.avi'; 'twoMonkeys'; 'socialInteraction'; 'observing'}; ...

{'humanForaging_1181.avi'; 'twoHumans'; 'socialInteraction'; 'foraging'}; ...
{'monkeyForaging_1181.avi'; 'twoMonkeys'; 'socialInteraction'; 'foraging'}; ...
{'monkeyForaging_1182.avi'; 'twoMonkeys'; 'socialInteraction'; 'foraging'}; ...
{'monkeyForaging_1183.avi'; 'twoMonkeys'; 'socialInteraction'; 'foraging'}; ...
{'monkeyForaging_1184.avi'; 'twoMonkeys'; 'socialInteraction'; 'foraging'}; ...
{'monkeyForaging_1185.avi'; 'twoMonkeys'; 'socialInteraction'; 'foraging'}; ...

{'humanSitting_1191.avi'; 'twoHumans'; 'socialInteraction'; 'sitting'}; ...
{'monkeySitting_1191.avi'; 'twoMonkeys'; 'socialInteraction'; 'sitting'}; ...
{'monkeySitting_1192.avi'; 'twoMonkeys'; 'socialInteraction'; 'sitting'}; ...
{'monkeySitting_1193.avi'; 'twoMonkeys'; 'socialInteraction'; 'sitting'}; ...
{'monkeySitting_1194.avi'; 'twoMonkeys'; 'socialInteraction'; 'sitting'}; ...
{'monkeySitting_1195.avi'; 'twoMonkeys'; 'socialInteraction'; 'sitting'}; ...

{'humanGoalDir_1201.avi'; 'twoHumans'; 'nonInteraction'; 'goalDir'}; ...
{'humanGoalDir_1202.avi'; 'twoHumans'; 'nonInteraction'; 'goalDir'}; ...
{'humanGoalDir_1203.avi'; 'twoHumans'; 'nonInteraction'; 'goalDir'}; ...
{'humanGoalDir_1204.avi'; 'twoHumans'; 'nonInteraction'; 'goalDir'}; ...
{'humanGoalDir_1205.avi'; 'twoHumans'; 'nonInteraction'; 'goalDir'}; ...
{'monkeyGoalDir_1201.avi'; 'twoMonkeys'; 'nonInteraction'; 'goalDir'}; ...
{'monkeyGoalDir_1202.avi'; 'twoMonkeys'; 'nonInteraction'; 'goalDir'}; ...
{'monkeyGoalDir_1203.avi'; 'twoMonkeys'; 'nonInteraction'; 'goalDir'}; ...
{'monkeyGoalDir_1204.avi'; 'twoMonkeys'; 'nonInteraction'; 'goalDir'}; ...
{'monkeyGoalDir_1205.avi'; 'twoMonkeys'; 'nonInteraction'; 'goalDir'}; ...

{'humanIdle_1301.avi'; 'twoHumans'; 'nonInteraction'; 'idle'}; ...
{'humanIdle_1302.avi'; 'twoHumans'; 'nonInteraction'; 'idle'}; ...
{'humanIdle_1303.avi'; 'twoHumans'; 'nonInteraction'; 'idle'}; ...
{'humanIdle_1304.avi'; 'twoHumans'; 'nonInteraction'; 'idle'}; ...
{'humanIdle_1305.avi'; 'twoHumans'; 'nonInteraction'; 'idle'}; ...
{'monkeyIdle_1301.avi'; 'twoMonkeys'; 'nonInteraction'; 'idle'}; ...
{'monkeyIdle_1302.avi'; 'twoMonkeys'; 'nonInteraction'; 'idle'}; ...
{'monkeyIdle_1303.avi'; 'twoMonkeys'; 'nonInteraction'; 'idle'}; ...
{'monkeyIdle_1304.avi'; 'twoMonkeys'; 'nonInteraction'; 'idle'}; ...
{'monkeyIdle_1305.avi'; 'twoMonkeys'; 'nonInteraction'; 'idle'}; ...
};

pictureLabels = {...
'scramble1'; ...
'scramble2'; ...
'scramble3'; ...
'scramble4'; ...
'scramble5'; ...

'landscape1'; ...
'landscape2'; ...
'landscape3'; ...
'landscape4'; ...
'landscape5'; ...

'objects1'; ...
'objects2'; ...
'objects3'; ...
'objects4'; ...
'objects5'; ...

'humanChasing1'; ...
'monkeyChasing1'; ...
'monkeyChasing2'; ...
'monkeyChasing3'; ...
'monkeyChasing4'; ...
'monkeyChasing5'; ...

'humanFighting1'; ...
'monkeyFighting1'; ...
'monkeyFighting2'; ...
'monkeyFighting3'; ...
'monkeyFighting4'; ...
'monkeyFighting5'; ...

'humanMounting1'; ...
'monkeyMounting1'; ...
'monkeyMounting2'; ...
'monkeyMounting3'; ...
'monkeyMounting4'; ...
'monkeyMounting5'; ...

'humanGrooming1'; ...
'monkeyGrooming1'; ...
'monkeyGrooming2'; ...
'monkeyGrooming3'; ...
'monkeyGrooming4'; ...
'monkeyGrooming5'; ...

'humanHolding1'; ...
'monkeyHolding1'; ...
'monkeyHolding2'; ...
'monkeyHolding3'; ...
'monkeyHolding4'; ...
'monkeyHolding5'; ...

'humanFollowing1'; ...
'monkeyFollowing1'; ...
'monkeyFollowing2'; ...
'monkeyFollowing3'; ...
'monkeyFollowing4'; ...
'monkeyFollowing5'; ...

'humanObserving1'; ...
'monkeyObserving1'; ...
'monkeyObserving2'; ...
'monkeyObserving3'; ...
'monkeyObserving4'; ...
'monkeyObserving5'; ...

'humanForaging1'; ...
'monkeyForaging1'; ...
'monkeyForaging2'; ...
'monkeyForaging3'; ...
'monkeyForaging4'; ...
'monkeyForaging5'; ...

'humanSitting1'; ...
'monkeySitting1'; ...
'monkeySitting2'; ...
'monkeySitting3'; ...
'monkeySitting4'; ...
'monkeySitting5'; ...

'humanGoalDir1'; ...
'humanGoalDir2'; ...
'humanGoalDir3'; ...
'humanGoalDir4'; ...
'humanGoalDir5'; ...
'monkeyGoalDir1'; ...
'monkeyGoalDir2'; ...
'monkeyGoalDir3'; ...
'monkeyGoalDir4'; ...
'monkeyGoalDir5'; ...

'humanIdle1'; ...
'humanIdle2'; ...
'humanIdle3'; ...
'humanIdle4'; ...
'humanIdle5'; ...
'monkeyIdle1'; ...
'monkeyIdle2'; ...
'monkeyIdle3'; ...
'monkeyIdle4'; ...
'monkeyIdle5'; ...
};


save('StimParamFileSocialVids_V2.mat','paramArray','categoryLabels','pictureLabels')


