function [ ] = buildStimParamFileSocialVids_Auto()
%Creates a .m file containing cell arrays detailing the parameters of a
%particular stimulus set.

%File produced 2 Cell Arrays. The first is a ParamArray, with the name of
%the video. {{VideoID1; {label1}; {label2}...}{VideoID2; {label1};
%{label2}...}. The second is a TriggerLabels, containing all possible labels. 

% For experiment run 2018.10.10
% Updated 2019.13.1 to include full stim set, including August stuff.

%Find the folder with what you want
fprintf('Select folder containing files...\n');
%StimFolder = uigetdir();
StimFolder = {'G:\StimuliForFaridfromJulia\SocialDecomposed_renamed', 'G:\StimuliForFaridfromJulia\SocialCategories' };


%Find every file in this folder with the extension desired.
%Add other files
for ii = 1:length(StimFolder)
  tmpStimFiles = dir(StimFolder{ii});
  tmpStimFiles = tmpStimFiles(3:end); %Remove the '.' and '..'
  if ii == 1
    tmpStimFilesStack = tmpStimFiles;
  else
    tmpStimFilesStack = [tmpStimFilesStack; tmpStimFiles];
  end
end

tmpStimFiles = tmpStimFilesStack;

%Anything that is not a directory, add to the list...

stimInd = find([tmpStimFiles.isdir] == 0);
if ~isempty(stimInd)
    stimList = cell(length(stimInd),1);
    for ii = 1:length(stimInd)
        stimList{ii} = tmpStimFiles(stimInd(ii)).name;
    end
else
    stimList = cell(0);
end

%Look through the remaining lists, going as deep as needed.
dirInd = find([tmpStimFiles.isdir] == 1);
for ii = 1:length(dirInd)
  tmpStimFolder = dir([tmpStimFiles(dirInd(ii)).folder filesep tmpStimFiles(dirInd(ii)).name]);
  subStimFolder = struct2cell(tmpStimFolder(3:end));
  subStimList = subStimFolder(1,:)';
  stimList = vertcat(stimList, subStimList);
end

%% Turn that list into the appropriate file for phyzzy..
%pictureLabels = split(stimList, '.'); %Due to some names being
%.avi_Dephased.avi, split won't work. Going to just chop off the last 4
%characters, assuming these are a 3 character extension + dot.

pictureLabels = cellfun(@(x) x(1:end-4), stimList, 'UniformOutput', false);


for ii = 1:length(stimList)
  stim = stimList{ii};
  stimParts = split(stim,["_","."]);
  code = stimParts{2};
  stimLabels = cell(1);
  switch code(1)
    case '1';            stimLabels{1} = 'agents';
    case '2';            stimLabels{1} = 'objects';
    case '3';            stimLabels{1} = 'scramble';
    case '4';            stimLabels{1} = 'scene'; stimLabels{2} = 'nonInteraction';
  end
  switch code(2)
    case '0';            stimLabels = horzcat(stimLabels, 'N/A');
    case '1';            stimLabels = horzcat(stimLabels, 'interaction');
    case '2';            stimLabels = horzcat(stimLabels, 'goalDirectedorMoving');
    case '3';            stimLabels = horzcat(stimLabels, 'Still/Idle', 'nonInteraction');
  end
  switch code(3)
    case '0';            stimLabels = horzcat(stimLabels, 'N/A');   
    case '1';            stimLabels = horzcat(stimLabels, 'socialInteraction','chasing');
    case '2';            stimLabels = horzcat(stimLabels, 'socialInteraction','fighting');
    case '3';            stimLabels = horzcat(stimLabels, 'socialInteraction','mounting');
    case '4';            stimLabels = horzcat(stimLabels, 'socialInteraction','grooming');
    case '5';            stimLabels = horzcat(stimLabels, 'socialInteraction','holding');
    case '6';            stimLabels = horzcat(stimLabels, 'socialInteraction','following');
    case '7';            stimLabels = horzcat(stimLabels, 'socialInteraction','observing');
    case '8';            stimLabels = horzcat(stimLabels, 'socialInteraction','foraging');
    case '9';            stimLabels = horzcat(stimLabels, 'socialInteraction','sitting');
  end
  if (length(stimParts) == 3)
      stimLabels = horzcat(stimLabels, 'faces','bodies','hands','background');
  end
  if (length(stimParts) == 4) && strcmp(stimParts{3}, 'Dephased')
      stimLabels = {'scramble'};
  end
  if (length(stimParts) > 3) && strncmpi(stimParts(3),'Decomp',6)
    switch stimParts{3}
        case 'DecompA'
            switch stimParts{4}
                case 'B';   stimLabels = horzcat(stimLabels, 'faces','background');
                case 'F';   stimLabels = horzcat(stimLabels, 'bodies', 'hands','background');
                case 'H';   stimLabels = horzcat(stimLabels, 'bodies', 'faces','background');
                case 'FB';  stimLabels = horzcat(stimLabels, 'background');
                case 'FH';  stimLabels = horzcat(stimLabels, 'bodies','background');
            end
        case 'DecompB'
            switch stimParts{4}
                case 'B';   stimLabels = horzcat(stimLabels, 'bodies','hands');
                case 'F';   stimLabels = horzcat(stimLabels, 'faces');
                case 'H';   stimLabels = horzcat(stimLabels, 'hands');
                case 'FB';  stimLabels = horzcat(stimLabels, 'faces', 'bodies');
                case 'FH';  stimLabels = horzcat(stimLabels, 'faces', 'hands');
            end
    end    
  end
  stimList{ii} = horzcat(stimList{ii}, stimLabels);
end

%% Non-coded, manuel inputs from October
paramArrayB = {...
{'scramble_3001.avi', 'scramble'}; ...
{'scramble_3002.avi', 'scramble'}; ...
{'scramble_3003.avi', 'scramble'}; ...
{'scramble_3004.avi', 'scramble'}; ...
{'scramble_3005.avi', 'scramble'}; ...

{'landscape_4001.avi', 'landscape'}; ...
{'landscape_4002.avi', 'landscape'}; ...
{'landscape_4003.avi', 'landscape'}; ...
{'landscape_4004.avi', 'landscape'}; ...
{'landscape_4005.avi', 'landscape'}; ...

{'objects_2101.avi', 'objects', 'interaction', 'goalDirectedOrMoving'}; ...
{'objects_2102.avi', 'objects', 'interaction', 'goalDirectedOrMoving'}; ...
{'objects_2103.avi', 'objects', 'interaction', 'goalDirectedOrMoving'}; ...
{'objects_2104.avi', 'objects', 'interaction', 'goalDirectedOrMoving'}; ...
{'objects_2105.avi', 'objects', 'interaction', 'goalDirectedOrMoving'}; ...
};

pictureLabelsB = {...
'scramble1'; ...
'scramble2'; ...
'scramble3'; ...
'scramble4'; ...
'scramble5'; ...

'landscape1'; ...
'landscape2'; ...
'landscape3'; ...
'landscape4'; ...
'landscape5'; ...

'objects1'; ...
'objects2'; ...
'objects3'; ...
'objects4'; ...
'objects5'; ...
};

stimList = vertcat(stimList, paramArrayB);

%% August stimParam

paramArrayC = {...
{'Cut_obj_interact1_1.avi', 'objects', 'goalDirectedOrMoving'}; ...
{'Cut_obj_interact1_2.avi', 'objects', 'goalDirectedOrMoving'}; ...
{'Cut_Order1Interaction_1.avi', 'socialInteraction', 'chasing'}; ...
{'Cut_Order1Interaction_2.avi', 'socialInteraction', 'fighting'}; ...
{'Cut_Order1Interaction_3.avi', 'socialInteraction', 'grooming'}; ...
{'Cut_Order1Interaction_4.avi', 'socialInteraction', 'grooming'}; ...
{'Cut_Order1Interaction_5.avi', 'socialInteraction', 'mounting'}; ...
{'Cut_Order2Interaction_1.avi', 'socialInteraction', 'fighting'}; ...
{'Cut_Order2Interaction_2.avi', 'socialInteraction', 'grooming'}; ...
{'Cut_Order2Interaction_3.avi', 'socialInteraction', 'mounting'}; ...
{'Cut_Order2Interaction_4.avi', 'socialInteraction', 'grooming'}; ...
{'Cut_Order2Interaction_5.avi', 'socialInteraction', 'mounting'}; ...
{'Cut_Order2LandscapesFull_1.avi', 'scene'}; ...
{'Cut_Order2LandscapesFull_2.avi', 'scene'}; ...
{'Order1GoalLeft_1_Order1GoalRight_1.avi','interaction', 'goalDirectedOrMoving'}; ...
{'Order1GoalLeft_2_Order1GoalRight_2.avi','interaction', 'goalDirectedOrMoving'}; ...
{'Order1GoalLeft_3_Order1GoalRight_3.avi','interaction', 'goalDirectedOrMoving'}; ...
{'Order1GoalLeft_4_Order1GoalRight_4.avi','interaction', 'goalDirectedOrMoving'}; ...
{'Order1GoalLeft_5_Order1GoalRight_5.avi','interaction', 'goalDirectedOrMoving'}; ...
{'Order1MonkLeft_1_Order1MonkRight_1.avi','nonInteraction', 'idle'}; ...
{'Order1MonkLeft_2_Order1MonkRight_2.avi','nonInteraction', 'idle'}; ...
{'Order1MonkLeft_3_Order1MonkRight_3.avi','nonInteraction', 'idle'}; ...
{'Order1MonkLeft_4_Order1MonkRight_4.avi','nonInteraction', 'idle'}; ...
{'Order1MonkLeft_5_Order1MonkRight_5.avi','nonInteraction', 'idle'}; ...

{'Dephased_Order1Interaction_1.avi', 'scramble'}; ...
{'Dephased_Order1Interaction_2.avi', 'scramble'}; ...
{'Dephased_Order1Interaction_3.avi', 'scramble'}; ...
{'Dephased_Order1Interaction_4.avi', 'scramble'}; ...

{'Dephased_Order2Interaction_1.avi', 'scramble'}; ...
{'Dephased_Order2Interaction_2.avi', 'scramble'}; ...
{'Dephased_Order2Interaction_3.avi', 'scramble'}; ...
{'Dephased_Order2Interaction_4.avi', 'scramble'}; ...
{'Dephased_Order2Interaction_5.avi', 'scramble'}; ...

{'Cut_human_interaction_1.avi', 'socialInteraction', 'chasing'}; ...
{'Cut_human_interaction_2.avi', 'socialInteraction', 'walking'}; ...
{'Cut_human_interaction_3.avi', 'socialInteraction', 'grooming'}; ...
{'Cut_human_interaction_4.avi', 'socialInteraction', 'fighting'}; ...
{'Cut_human_interaction_5.avi', 'socialInteraction', 'mounting'}; ...

{'human_alone1_1_2_human_alone2_1_2.avi','nonInteraction', 'idle'}; ...
{'human_alone1_1_3_human_alone2_1_3.avi','nonInteraction', 'idle'}; ...
{'human_goal1_1_4_human_goal2_1_4.avi','nonInteraction', 'goalDirectedOrMoving'}; ...
{'human_goal1_1_5_human_goal2_1_5.avi','nonInteraction','goalDirectedOrMoving'}; ...

{'Cut_Order1Chasing1.avi', 'socialInteraction', 'chasing','highMotion'}; ...
{'Cut_Order1Chasing2.avi', 'socialInteraction', 'chasing','highMotion'}; ...
{'Cut_Order1Chasing3.avi', 'socialInteraction', 'chasing','highMotion'}; ...
{'Cut_Order1Chasing4.avi', 'socialInteraction', 'chasing','highMotion'}; ...
{'Cut_Order1Chasing5.avi', 'socialInteraction', 'chasing','highMotion'}; ...

{'Cut_Order1Mounting1.avi', 'socialInteraction', 'chasing','highMotion'}; ...
{'Cut_Order1Mounting2.avi', 'socialInteraction', 'chasing','highMotion'}; ...
{'Cut_Order1Mounting4.avi', 'socialInteraction', 'chasing','highMotion'}; ...
{'Cut_Order1Mounting5.avi', 'socialInteraction', 'chasing','highMotion'}; ...

{'Cut_Order1Fighting1.avi', 'socialInteraction', 'fighting','highMotion'}; ...
{'Cut_Order1Fighting2.avi', 'socialInteraction', 'fighting','highMotion'}; ...
{'Cut_Order1Fighting2.avi', 'socialInteraction', 'fighting','highMotion'}; ...
{'Cut_Order1Fighting4.avi', 'socialInteraction', 'fighting','highMotion'}; ...
{'Cut_Order1Fighting5.avi', 'socialInteraction', 'fighting','highMotion'}; ...

{'Dephased_Order1Interactionchasing.avi', 'scramble', 'highMotion'}; ...
{'Dephased_Order1Interactionfighting.avi', 'scramble', 'highMotion'}; ...
};

pictureLabelsC = {...
  'Objects1'; ...
  'Objects2'; ...
  
  'monkeyChasing1'; ...
  'monkeyFighting1'; ...
  'monkeyGrooming1'; ...
  'monkeyGrooming2'; ...
  'monkeyMounting1'; ...
  'monkeyFighting2'; ...
  'monkeyGrooming3'; ...
  'monkeyMounting2'; ...
  'monkeyGrooming4'; ...
  'monkeyMounting3'; ...
  'Landscape1'; ...
  'Landscape2'; ...
  
  'monkeyGoalDirected1'; ...
  'monkeyGoalDirected2'; ...
  'monkeyGoalDirected3'; ...
  'monkeyGoalDirected4'; ...
  'monkeyGoalDirected5'; ...
  
  'monkeyIdle1'; ...
  'monkeyIdle2'; ...
  'monkeyIdle3'; ...
  'monkeyIdle4'; ...
  'monkeyIdle5'; ...
  
  'scramble1a';...
  'scramble2a';...
  'scramble3a';...
  'scramble4a';...
  
  'scramble5a';...
  'scramble6a';...
  'scramble7a';...
  'scramble8a';...
  'scramble9a';...
  
  'humanChasing1'; ...
  'humanWalking1'; ...
  'humanGrooming1'; ...
  'humanFighting1'; ...
  'humanMating1'; ...
  
  'humanIdle1'; ...
  'humanIdle2'; ...
  'humanGoalDirected1'; ...
  'humanGoalDirected2'; ...
  
  'monkeyChasing2a'; ...
  'monkeyChasing3a'; ...
  'monkeyChasing1a'; ...
  'monkeyChasing4a'; ...
  'monkeyChasing5a'; ...
  
  'monkeyMounting2a'; ...
  'monkeyMounting3a'; ...
  'monkeyMounting4a'; ...
  'monkeyMounting5a'; ...
  
  'monkeyFighting1a'; ...
  'monkeyFighting2a'; ...
  'monkeyFighting3a'; ...
  'monkeyFighting4a'; ...
  'monkeyFighting5a'; ...
  
  'scramble10';...
  'scramble11';...
  };

stimList = vertcat(stimList, paramArrayC);

%% Package Outputs
pictureLabels = pictureLabels(:,1);
pictureLabels = vertcat(pictureLabels, pictureLabelsB);
pictureLabels = vertcat(pictureLabels, pictureLabelsC);

categoryLabels = {'agents', 'objects', 'scramble', 'scene', 'interaction', 'nonInteraction', 'socialInteraction',...
  'goalDirectedOrMoving', 'StillIdle', 'chasing', 'fighting', 'mounting', 'grooming', 'holding', 'following', 'observing',...
  'foraging','sitting','faces','bodies','hands','background'};
  
paramArray = stimList;

% pictureLabels = {}    %labelscheme
%     %loop through stimList, maybe move to loop above
%     %If the name is 3 long (inc .avi), name + 4th code number
%     %If it is 4 long, name + scramble
%     %If it is 5 long, look at DecompA or B, add word "minus" or "plus",
%     %then add labels as single letters.
%     pictureLabels

save('StimParamFileSocialVids_Full.mat','paramArray','categoryLabels','pictureLabels')